title: FlashAir Developers
description: FlashAir Developers Website Archive
theme: just-the-docs
encding: utf-8
github : 
  - metadata
repository: flashair-developers/website
search_enabled: true
plugins: 
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap
